### PR TITLE
fix trading lending state

### LINKED ISSUE #181: tomox: infinite loop and chain stop
```bash
                                                          quantityToTrade=13000000000000000000
DEBUG[03-14|09:57:15] processLimitOrder                        side=SELL maxPrice=22900000     orderPrice=22800000     volume=4000000000000000000
DEBUG[03-14|09:57:15] Max price in bids tree                   price=22900000
DEBUG[03-14|09:57:15] Process matching between order and orderlist quantityToTrade=13000000000000000000
DEBUG[03-14|09:57:15] found order                              orderId =000000…000022 side=     amount=0
DEBUG[03-14|09:57:15] New trade found                          newTrades=[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                


quantityToTrade=13000000000000000000
DEBUG[03-14|09:57:15] processLimitOrder                        side=SELL maxPrice=22900000     orderPrice=22800000     volume=4000000000000000000
DEBUG[03-14|09:57:15] Max price in bids tree                   price=22900000
DEBUG[03-14|09:57:15] Process matching between order and orderlist quantityToTrade=13000000000000000000
DEBUG[03-14|09:57:15] found order                              orderId =000000…000022 side=     amount=0
DEBUG[03-14|09:57:15] New trade found                          newTrades=[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

quantityToTrade=13000000000000000000
DEBUG[03-14|09:57:15] processLimitOrder                        side=SELL maxPrice=22900000     orderPrice=22800000     volume=4000000000000000000
DEBUG[03-14|09:57:15] Max price in bids tree                   price=22900000
DEBUG[03-14|09:57:15] Process matching between order and orderlist quantityToTrade=13000000000000000000
DEBUG[03-14|09:57:15] found order                              orderId =000000…000022 side=     amount=0
DEBUG[03-14|09:57:15] New trade found                          newTrades=[]     
```

It happens more frequently when we send many orders in a short time

amount = 0 at https://github.com/tomochain/tomochain/blob/51899d410e2b36b42673b34b4770fcb498f8c87b/tomox/order_processor.go#L218

### PR DESCRIPTION
**Pull request by nguyenbatam**

### CODE REVIEW

File: core/lending_pool_test.go [hunk 1]
```diff
@@ -146,26 +145,28 @@ func testSendLending(t *testing.T, amount *big.Int, interest uint64, side string
 
 func TestSendLending(t *testing.T) {
```
Comment (thanhnguyennguyen) [inline core/lending_pool_test.go:146]: `t.SkipNow()` 
to skip this test in travis

**Review by thanhnguyennguyen — CHANGES_REQUESTED** [review]

File: core/order_pool_test.go [hunk 2]
```diff
@@ -264,29 +264,31 @@ func TestFilled(t *testing.T) {
...
-	testSendOrderTOMOBTC(t, new(big.Int).Mul(big.NewInt(1200000), _1E18), TOMOBTCPrice, "SELL", "NEW", 0)
-
-	TOMOUSDPrice := new(big.Int).Mul(big.NewInt(10000000000000), big.NewInt(60000)) // 0.6
-	time.Sleep(5 * time.Second)
-	testSendOrderTOMOUSD(t, new(big.Int).Mul(big.NewInt(600000), _1E18), TOMOUSDPrice, "BUY", "NEW", 0)
-	time.Sleep(5 * time.Second)
-	testSendOrderTOMOUSD(t, new(big.Int).Mul(big.NewInt(600000), _1E18), TOMOUSDPrice, "BUY", "NEW", 0)
-	time.Sleep(5 * time.Second)
-	testSendOrderTOMOUSD(t, new(big.Int).Mul(big.NewInt(1200000), _1E18), TOMOUSDPrice, "SELL", "NEW", 0)
+	for true {
```
Comment (thanhnguyennguyen) [inline core/order_pool_test.go]: tests ran too long due to this one
Please don't commit this change

**Review by thanhnguyennguyen — CHANGES_REQUESTED** [review]

**Review by thanhnguyennguyen — APPROVED** [review]

**Review by thanhson1085 — APPROVED** [review]
