### PR TITLE
fix error balance matching order

### LINKED ISSUE #20: Wrong matching for relayerowner order
Issue when relayerowner create an order, and the order is matched, matching engine works incorrectly

### PR DESCRIPTION
**Pull request by nguyenbatam**
resolve #20

### CODE REVIEW

**Review by thanhnguyennguyen — APPROVED** [review]

File: tomox/order_processor.go [hunk 1]
```diff
@@ -621,6 +621,8 @@ func SetteBalance(coinbase common.Address, takerOrder, makerOrder *tomox_state.O
 	if mapBalances[settleBalance.Taker.InToken] == nil {
 		mapBalances[settleBalance.Taker.InToken] = map[common.Address]*big.Int{}
 		mapBalances[settleBalance.Taker.InToken][takerOrder.UserAddress] = newTakerInTotal
+	}else {
```
Comment (thanhnguyennguyen) [inline tomox/order_processor.go]: refactor a bit
```
	if mapBalances[settleBalance.Taker.OutToken] == nil {
		mapBalances[settleBalance.Taker.OutToken] = map[common.Address]*big.Int{}
	}
	mapBalances[settleBalance.Taker.OutToken][takerOrder.UserAddress] = newTakerOutTotal
```

**Review by thanhson1085 — APPROVED** [review]
